### ISSUE TITLE
Question about Audio pretransform pkl file

### ISSUE THREAD

**Issue by c1ircle** [GeWu-Lab/bias_in_AVS#1]
Thanks for your great work! Could you please share the pkl file for the audio pretransform?

**Comment by PeiwenSun2000** [comment]
Thanks for your attention. Please kindly refer to [FAQ](https://github.com/GeWu-Lab/bias_in_AVS?tab=readme-ov-file#faq).

We provided both the code and the corresponding format. The re-implementation should be rather easy.
