### ISSUE TITLE
The extracted audio pkl file

### ISSUE THREAD

**Issue by YenanLiu** [GeWu-Lab/bias_in_AVS#3]
Hi authors,

Could you please provide the clustered and classification audio pkl file to help reproduce your superior results? In your paper, you just mention using VGGish as the audio backbone, so what is the classification structure in your implementation? Just a linear layer like Beats? Did you train the whole model or just the classification head? It's so confusing. I guess the classification results may have a significant effect on the final results.

**Comment by PeiwenSun2000** [comment]
Thanks for your attention.

In my implementation, I just simply update a classification head. But if you train the whole model, I assume there will be potential gain.

The implementation of clustering and classification is not that hard. Actually setting all queries as active queries can at least run the whole project, which will help you to understand this work.
